config/routes.rb
Rails.application.routes.draw do
  get 'documents/create'
  get 'documents/edit'
  get 'documents/update'
  get 'documents/show'
  get 'documents/new'
  get 'documents/destroy'
  get 'clients/new'
  get 'clients/edit'
  get 'clients/index'
  get 'clients/show'
  get 'clients/destroy'
  get 'bills/new'
  get 'bills/edit'
  get 'bills/update'
  get 'bills/show'
  get 'bills/destroy'
  get 'messages/create'
  get 'messages/new'
  get 'messages/edit'
  get 'messages/update'
  get 'messages/show'
  get 'messages/destroy'

  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'password_resets/edit'
  get 'password_resets/new'
  get 'sessions/new'
  get 'users/new'

  root 'static_pages#home'
  get '/home',       to: 'static_pages#home'
  get '/about',      to: 'static_pages#about'
  get '/resume',     to: 'static_pages#resume'
  get '/services',   to: 'static_pages#services'
  get '/contact',    to: 'static_pages#contact'
  resources :messages
  resources :documents
  resources :clients
  resources :bills
  resources :users do
    member do
      get :messages
      get :clients
      get :bills
      get :documents
    end
    resources :messages 
    resources :clients
    resources :bills
    resources :documents
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :bills, dependent: :destroy 
    has_many :messages, dependent: :destroy 
    validates :email, uniqueness: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def create
    @client = Client.new(client_params)
    if @client.save 
      flash[:success] = 'Client Created!'
      redirect_to client_path(@client)
    else 
      redirect_to request.referer || clients_path
    end
  end
  
  def new 
    @client = Client.new
  end
  
  def index
    @clients = Client.paginate(page: params[:page])
  end

  def edit
    @client = Client.find_by(id: params[:format])
  end

  def update
    @client = Client.find_by(id: params[:id])
    if @client.update_attributes(client_params)
      flash[:success] = 'Client successfully updated!'
      redirect_to @client
    else
      render 'edit'
    end
  end

  def show
    @client = Client.find_by(id: params[:id])
    @billTotal = @client.bills.where(paid: false).sum(:total)
    @messages = @client.messages.paginate(page: params[:page])
    @reply = Message.new
  end

  def destroy
    @client = Client.find_by(id: params[:id])
    @client.destroy
    flash[:success] = 'Client deleted'
    redirect_to request.referer || clients_path
  end
  
  private
  
  def client_params
    params.require(:client).permit(:name, 
                                    :phone,
                                    :email,
                                    :relation,
                                    :billing_status,
                                    :amount_billed,
                                    :previous_work)
  end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/clients/_client.html.erb
<div class='col-md-12 col-sm-12 col-xs-12 center client-holder'>
    <div class='col-md-12 col-sm-12 col-xs-12'>
        <h1 class='col-md-5 col-sm-5 col-xs-12' style='margin-left: 5px'>
            <%= link_to client.name, client_path(client), 
                                     title: "Client's Profile" %>
        </h1>
        <h3 class='pull-right col-md-3'>
            <%= link_to 'Messages', messages_show_path(client.id), 
                                    title: "Client's Messages" %> 
             (<%= client.messages.count %>) 
        </h3>
        <h3 class='pull-right col-md-2'>
            <%= link_to 'Bills', bills_show_path(client.id), 
                title: "Client's Bills" %> (<%= client.bills.count %>)
        </h3>
        <div class='container pull-right buffer name 
                    col-md-10 col-sm-10 col-xs-12'>
            <div class='container col-md-4 col-sm-7 col-xs-12'>
                <div class='holder col-md-8 col-sm-5 col-xs-12'>
                    Email: 
                </div> 
                <div class='client col-md-12 col-sm-12 col-xs-11'>
                    <%= client.email %>
                </div>
            </div>
            <div class='container col-md-3 col-sm-5 col-xs-12'>
                <div class='holder col-md-8 col-sm-5 col-xs-12'>
                    Phone: 
                </div>
                <div class='client col-md-12 col-sm-12 col-xs-11'>
                    <%= client.phone %>
                </div>
            </div>
            <% if client.relation then %>
                <div class='container col-md-4 col-sm-5 col-xs-12'>
                    <div class='holder col-md-8 col-sm-8 col-xs-12'>
                        Relation: 
                    </div>
                    <div class='client col-md-12 col-sm-12 col-xs-11'>
                        <% if client.relation == '' %>
                            Not Specified
                        <% else %>
                            <%= client.relation %>
                        <% end %>
                    </div>
                </div>
                <div class='container col-md-4 col-sm-4 col-xs-12'>
                    <div class='holder col-md-8 col-sm-9 col-xs-12'>
                        Amount due: 
                    </div>
                    <div class='client col-md-12 col-sm-12 col-xs-11'>
                        <%= link_to client.bills.where(paid: false).sum(:total), 
                                    bills_show_path(client.id) %>
                    </div>
                </div>
                <div class='container col-md-3 col-sm-4 col-xs-12'>
                    <div class='holder col-md-8 col-sm-9 col-xs-12'>
                        Billing Status: 
                    </div>
                    <div class='client col-md-12 col-sm-12 col-xs-11'>
                        <% if client.bills.count == 0 %>
                            No Bills
                        <% elsif @billTotal == 0 %>
                            Paid
                        <% else %>
                            Bills Due
                        <% end %>
                    </div>
                </div>
                <div class='container col-md-4 col-sm-5 col-xs-12'>
                    <div class='holder col-md-8 col-sm-8 col-xs-12'>
                        Previous Work: 
                    </div>
                    <div class='client col-md-12 col-sm-12 col-xs-11'>
                        <% if client.previous_work == '' %>
                            Not Specified
                        <% else %>
                            <%= client.previous_work %>
                        <% end %>
                    </div>
                </div>
            <% else %>
                <div class='client link col-md-4 col-sm-4 col-xs-11'>
                    Edit this client to add more information to their profile!
                </div>
            <% end %>
        </div>
    </div>
    <div class='delete holder pull-right col-md-2 col-sm-3 col-xs-6 message-holder'>
        <%= link_to 'Message |', messages_new_path(client.id), 
                                 title: "Message Client" %>
        <%= link_to 'Bill |', bills_new_path(client.id), title: "Bill Client" %>
        <%= link_to 'Edit |', clients_edit_path(client.id), 
                              title: "Edit Client" %>
        <%= link_to 'Delete', client, method: :delete, title: "Delete Client",
                                  data: { confirm: 'You sure?' } %>
    </div>
</div>

app/views/clients/create.html.erb
<% provide(:title, 'New Client') %>
<%= render 'shared/client_form' %>

app/views/clients/destroy.html.erb
<h1>Client#destroy</h1>
<p>Find me in app/views/client/destroy.html.erb</p>

app/views/clients/edit.html.erb
<% provide(:title, 'Clients | Edit | ' + @client.name) %>

<%= render 'shared/client_form' %>

app/views/clients/index.html.erb
<% provide(:title, 'Clients') %>
<div class='container col-md-12 col-sm-12 col-xs-12'>
    <div class='col-md-12 col-sm-10 col-xs-12'>
        <h1 class='enter'>Clients</h1>
    </div>
    <div class='col-md-12 col-sm-10 col-xs-12'>
        <div class='pull-right para'>
            <%= link_to '+', clients_new_path, title: 'New Client' %>
        </div>
    </div>
    <div class='col-md-12 col-sm-10 col-xs-12 holder'>
        <div class='container col-md-2 col-sm-2 col-xs-2 sidebar'>
            
        </div>
        <div class='container message-holder center col-md-10 col-sm-10 col-xs-10'>
            <% if @clients.count == 0 %>
                <h3 class='col-md-12 col-sm-11 col-xs-12 para client center'>
                    No Clients
                </h3>
            <% else %>
                <%= will_paginate %>
                
                <%= render @clients %>
                
                <%= will_paginate %>
            <% end %>
        </div>
    </div>
</div>

app/views/clients/new.html.erb
<% provide(:title, 'New Client') %>
<%= render 'shared/client_form' %>

app/views/clients/show.html.erb
<% provide(:title, @client.name) %>
<div class='col-md-12 col-sm-12 col-xs-12'>
    <%= link_to 'All Clients', clients_url %>
    <h1 class='enter col-md-12 col-sm-12 col-xs-12'>Client Profile</h1>
    <%= render @client %>
    
    <% if @client.messages.count == 0 %>
        <h3 class='user col-md-12 col-sm-12 col-xs-12'>No messages with <%= @client.name %></h3>
    <% else %>
        <h3 class='user col-md-12 col-sm-12 col-xs-12'>Messages with <%= @client.name %></h3>
        <%= render @messages %>
    <% end %>
    <%= render 'shared/message_reply' %>
</div>