config/routes.rb
Rails.application.routes.draw do
  get 'documents/create'
  get 'documents/edit'
  get 'documents/update'
  get 'documents/show'
  get 'documents/new'
  get 'documents/destroy'
  get 'clients/new'
  get 'clients/edit'
  get 'clients/index'
  get 'clients/show'
  get 'clients/destroy'
  get 'bills/new'
  get 'bills/edit'
  get 'bills/update'
  get 'bills/show'
  get 'bills/destroy'
  get 'messages/create'
  get 'messages/new'
  get 'messages/edit'
  get 'messages/update'
  get 'messages/show'
  get 'messages/destroy'

  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'password_resets/edit'
  get 'password_resets/new'
  get 'sessions/new'
  get 'users/new'

  root 'static_pages#home'
  get '/home',       to: 'static_pages#home'
  get '/about',      to: 'static_pages#about'
  get '/resume',     to: 'static_pages#resume'
  get '/services',   to: 'static_pages#services'
  get '/contact',    to: 'static_pages#contact'
  resources :messages
  resources :documents
  resources :clients
  resources :bills
  resources :users do
    member do
      get :messages
      get :clients
      get :bills
      get :documents
    end
    resources :messages 
    resources :clients
    resources :bills
    resources :documents
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/bill.rb
class Bill < ApplicationRecord
    belongs_to :client 
    validates :total, presence: true
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def create
    @bill = Bill.new(bill_params)
    if @bill.save 
      flash[:success] = 'Bill Created!'
      redirect_to bill_path(@bill.client_id)
    else 
      redirect_to request.referer || bills_path
    end
  end
  
  def new
    @bill = Bill.new
  end

  def edit
    @bill = Bill.find_by(id: params[:format])
  end
  
  def update
    @bill = Bill.find_by(id: params[:id])
    if @bill.update_attributes(bill_params)
      flash[:success] = 'Bill updated!'
      redirect_to bills_show_path(@bill.client_id)
    else
      render 'edit'
    end
  end

  def show
    params[:id] = params[:id] || params[:format]
    @client = Client.find_by(id: params[:id])
  end

  def destroy
    @bill = Bill.find_by(id: params[:id])
    @bill.destroy
    flash[:success] = 'Bill deleted'
    redirect_to request.referer || bills_path
  end
  
  def index
    @bills = Bill.where(paid: false).paginate(page: params[:page])
    @billsAll = Bill.paginate(page: params[:page])
  end
  
  private 
  
  def bill_params
    params.require(:bill).permit(:total,
                                 :sent,
                                 :paid,
                                 :client_id,
                                 :comments)
  end
end

app/helpers/bill_helper.rb
module BillHelper
end

app/views/bills/_bill.html.erb
<div class='col-md-12 col-sm-12 col-xs-12 center client-holder'>
    <div class='col-md-2 col-sm-2 col-xs-12 center holder' 
         style='margin-top: 1px; padding-bottom: 2vw;'>
            <h5 class='link col-md-12 col-sm-12 col-xs-12' 
                style='margin-top: 2vw;'></h5>Update Status:</h5>
            <% if bill.paid == false %>
                <%= form_for(bill) do |f| %>
                  <%= f.hidden_field :paid, value: true %>
                  <%= f.submit 'Paid', title: 'Bill has been paid',  
                                       :class=> "client task-bubble link" %>
                <% end %>
            <% else %>
                <%= form_for(bill) do |f| %>
                  <%= f.hidden_field :paid, value: false %>
                  <%= f.submit 'Due', title: 'Bill is due',  
                                      :class=> "client task-bubble link due" %>
                <% end %>
            <% end %>
            <%= form_for(bill) do |f| %>
              <%= f.hidden_field :sent, value: true %>
              <%= f.submit 'Send', title: 'Send Bill Notification',  
                                   :class=> "client task-bubble link" %>
            <% end %>
    </div>
    <div class='col-md-9 col-sm-9 col-xs-12 name form-input'>
        <div>
            <h3 class='col-md-2 col-sm-5 col-xs-12' style='margin-left: 5px'>
                 $<%= link_to bill.total, bill_path(bill.client.id), 
                                          title: 'Client Profile'  %>
            </h3>
        </div>
        <div class='container col-md-2 col-sm-6 col-xs-12'>
            <div class='holder col-md-10 col-sm-5 col-xs-12'>Client: </div> 
            <div class='client col-md-12 col-sm-12 col-xs-11'>
                <%= link_to bill.client.name, client_path(bill.client) %>
            </div>
        </div>
        <div class='container col-md-2 col-sm-6 col-xs-12'>
            <div class='holder col-md-10 col-sm-5 col-xs-12'>Sent: </div> 
                <% if bill.sent == true %>
                <div class='client col-md-12 col-sm-12 col-xs-11'>
                    Yes
                 </div>
            <% else %>
                <div class='client due col-md-12 col-sm-12 col-xs-11'>
                    No
                 </div>
            <% end %>
        </div>
        <div class='container col-md-2 col-sm-6 col-xs-12'>
            <div class='holder col-md-12 col-sm-6 col-xs-12'>Paid: </div> 
            <% if bill.paid == true %>
                <div class='client col-md-12 col-sm-12 col-xs-11'>
                    Yes
                 </div>
            <% else %>
                <div class='client due col-md-12 col-sm-12 col-xs-11'>
                    No
                 </div>
            <% end %>
        </div>
        <div class='container col-md-3 col-sm-12 col-xs-12'>
            <div class='holder col-md-8 col-sm-5 col-xs-12'>Comments: </div> 
            <div class='client col-md-12 col-sm-12 col-xs-11'>
                <% if bill.comments == '' %>
                    No Comments
                <% else %>
                    <%= bill.comments %>
                <% end %>
            </div>
        </div>
    </div>
    <div class='delete holder pull-right col-md-2 col-sm-3 col-xs-6'>
        <%= link_to 'Edit |', bills_edit_path(bill.id), title: 'Edit Bill' %>
        <%= link_to 'Delete |', bill, method: :delete, title: 'Delete Bill', 
                                data: { confirm: 'You sure?' } %>
        <%= link_to "Client's Bills", bills_show_path(bill.client.id), 
                                      title: "Client's Bills"  %>
    </div>
</div>

app/views/bills/create.html.erb
<h1>Bill#create</h1>
<p>Find me in app/views/bill/create.html.erb</p>

app/views/bills/destroy.html.erb
<h1>Bill#destroy</h1>
<p>Find me in app/views/bill/destroy.html.erb</p>

app/views/bills/edit.html.erb
<% provide(:title, 'Bills | Edit | ' + @bill.client.name) %>
<%= render 'shared/bill_form' %>

app/views/bills/index.html.erb
<% provide(:title, 'Bills') %>
<div class='container col-md-12 col-sm-12 col-xs-12'>
    <div class='col-md-12 col-sm-11 col-xs-12'>
        <h1 class='enter'>Bills</h1>
    </div>
    <div class='col-md-2 col-sm-4 col-xs-4'>
        <h3 class='para link pull-left'>Due (<%= Bill.where(paid: false).count %>)</h3>
    </div>
    <div class='col-md-10 col-sm-8 col-xs-8'>
        <div class='pull-right para'>
            <%= link_to '+', bills_new_path, title: 'New Bill' %>
        </div>
    </div>
    <div class='col-md-12 col-sm-12 col-xs-12 holder'>
        <div class='container message-holder col-md-11 col-sm-12 col-xs-12'>
            <% if @bills.count == 0 %>
                <h3 class='col-md-12 col-sm-11 col-xs-12 para client center'>
                    No bills to be paid
                </h3>
            <% else %>
                <%= will_paginate %>
                
                <%= render @bills %>
                
                <%= will_paginate %>
            <% end %>
        </div>
    </div>
    <div class='col-md-12 col-sm-12 col-xs-12 pull-left'>
        <h3 class='para link pull-left'>All Bills (<%= Bill.count %>)</h3>
    </div>
    <div class='col-md-12 col-sm-112 col-xs-12 holder'>
        <div class='container message-holder col-md-11 col-sm-10 col-xs-10'>
            <% if @billsAll.count == 0 %>
                <h3 class='col-md-12 col-sm-11 col-xs-12 para client center'>
                    No bills
                </h3>
            <% else %>
                <%= will_paginate %>
                
                <%= render @billsAll %>
                
                <%= will_paginate %>
            <% end %>
        </div>
    </div>
</div>

app/views/bills/new.html.erb
<% provide(:title, 'New Bill') %>
<%= render 'shared/bill_form' %>

app/views/bills/show.html.erb
<% provide(:title, 'Bill for ' + @client.name) %>
<div class='pull-left'>
    <%= link_to 'All Bills', bills_url %>
</div></br>
<h1 class='enter'>Bills for <%= @client.name %></h1>
<div class='col-md-12 col-sm-12 col-xs-12'>
    <%= render @client.bills %>
</div>