config/routes.rb
Rails.application.routes.draw do
  get 'documents/create'
  get 'documents/edit'
  get 'documents/update'
  get 'documents/show'
  get 'documents/new'
  get 'documents/destroy'
  get 'clients/new'
  get 'clients/edit'
  get 'clients/index'
  get 'clients/show'
  get 'clients/destroy'
  get 'bills/new'
  get 'bills/edit'
  get 'bills/update'
  get 'bills/show'
  get 'bills/destroy'
  get 'messages/create'
  get 'messages/new'
  get 'messages/edit'
  get 'messages/update'
  get 'messages/show'
  get 'messages/destroy'

  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'password_resets/edit'
  get 'password_resets/new'
  get 'sessions/new'
  get 'users/new'

  root 'static_pages#home'
  get '/home',       to: 'static_pages#home'
  get '/about',      to: 'static_pages#about'
  get '/resume',     to: 'static_pages#resume'
  get '/services',   to: 'static_pages#services'
  get '/contact',    to: 'static_pages#contact'
  resources :messages
  resources :documents
  resources :clients
  resources :bills
  resources :users do
    member do
      get :messages
      get :clients
      get :bills
      get :documents
    end
    resources :messages 
    resources :clients
    resources :bills
    resources :documents
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/document.rb
class Document < ApplicationRecord
    belongs_to :user
    has_many :imgs  ## Added association
    has_many :img_attributes, :through => :imgs
    accepts_nested_attributes_for :imgs
    mount_uploader :img, DocumentUploader, :mount_on => :img
    validate :img_size_validation
 
    private
    
    def img_size_validation
        errors[:img] << "should be less than 2MB" if img.size > 2.megabytes
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def create
    @document = Document.new(document_params)
    if @document.save 
      flash[:success] = 'Document Uploaded!'
      redirect_to document_path(@document)
    else 
      flash[:danger] = @document.errors
      redirect_to request.referer || documents_path
    end
  end

  def edit
      @document = Document.find_by(id: params[:format])
  end

  def update
     @document = Document.find_by(id: params[:id])
    if @document.update_attributes(document_params)
      flash[:success] = 'Document successfully updated!'
      redirect_to documents_path
    else
      render 'edit'
    end
  end
  
  def new
    @document = Document.new
  end
  
  def index
    @documents = Document.paginate(page: params[:page])
  end

  def show
    params[:id] = params[:id] || params[:format]
    @document = Document.find_by(id: params[:id])
  end

  def destroy
    @document = Document.find_by(id: params[:id])
    @document.destroy
    flash[:success] = 'Document deleted'
    redirect_to documents_path
  end
  
  private
  
  def document_params
    params.require(:document).permit(:name,
                                     :tags,
                                     :client_id,
                                     :img)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div class='pull-left col-md-4 col-sm-12 col-xs-12'>
    <div class='holder col-md-12 col-sm-12 col-xs-12'>
        <% if document.img.present? %>
            <%= link_to documents_show_path(document), title: 'Document' do %>
              <%= image_tag(document.img.url, :class => 'col-md-12 col-sm-12 col-xs-12') %>
            <% end %>
        <% else %>
            <%= link_to documents_show_path(document), title: 'Document' do %>
              <%= image_tag('sample.png', :class => 'col-md-12 col-sm-12 col-xs-12') %>
            <% end %>
        <% end %>
    </div>
    <h3 class='para col-md-12 col-sm-12 col-xs-12'>
        <%= document.name %>
    </h3>
    <p class='link col-md-12 col-sm-12 col-xs-12'>
        <%= document.tags %>
    </p>
     <div class='delete document-action holder pull-right col-md-10 col-sm-10 col-xs-10'>
        <%= link_to 'Edit |', documents_edit_path(document.id), title: 'Edit Document' %>
        <%= link_to 'Delete', document, method: :delete, title: 'Delete Document', 
                                data: { confirm: 'You sure you would like to delete this Document?' } %>
    </div>
</div>

app/views/documents/create.html.erb
<h1>Documents#create</h1>
<p>Find me in app/views/documents/create.html.erb</p>

app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

app/views/documents/edit.html.erb
<% provide(:title, 'New Document') %>
<%= render 'shared/document_upload' %>

app/views/documents/index.html.erb
<% provide(:title, 'Documents') %>
<div class='container col-md-12 col-sm-11 col-xs-12'>
    <div class='col-md-12 col-sm-12 col-xs-12'>
        <h1 class='enter'>Documents</h1>
    </div>
    <div class='col-md-12 col-sm-12 col-xs-12'>
        <div class='pull-right para'>
            <%= link_to '+', documents_new_path, title: 'New Document' %>
        </div>
    </div>
    <div class='col-md-12 col-sm-11 col-xs-12 holder'>
        <div class='center photo-holder col-md-9 col-sm-9 col-xs-9'>
            <% if @documents.count == 0 %>
                <h3 class='col-md-12 col-sm-12 col-xs-12 para client center'>
                    No Documents
                </h3>
            <% else %>
                <%= will_paginate %>
                
                <%= render @documents %>
                
                <%= will_paginate %>
            <% end %>
        </div>
    </div>
</div>

app/views/documents/new.html.erb
<% provide(:title, 'New Document') %>
<%= render 'shared/document_upload' %>

app/views/documents/show.html.erb
<% provide(:title, 'Documents') %>
<div class='pull-left'>
    <%= link_to 'All Documents', documents_url %>
</div></br>
<div class='col-md-12 col-sm-12 col-xs-12 center document-holder'>
    <%= render @document %>
</div>

app/views/documents/update.html.erb
<h1>Documents#update</h1>
<p>Find me in app/views/documents/update.html.erb</p>