config/routes.rb
Rails.application.routes.draw do
  get 'documents/create'
  get 'documents/edit'
  get 'documents/update'
  get 'documents/show'
  get 'documents/new'
  get 'documents/destroy'
  get 'clients/new'
  get 'clients/edit'
  get 'clients/index'
  get 'clients/show'
  get 'clients/destroy'
  get 'bills/new'
  get 'bills/edit'
  get 'bills/update'
  get 'bills/show'
  get 'bills/destroy'
  get 'messages/create'
  get 'messages/new'
  get 'messages/edit'
  get 'messages/update'
  get 'messages/show'
  get 'messages/destroy'

  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'password_resets/edit'
  get 'password_resets/new'
  get 'sessions/new'
  get 'users/new'

  root 'static_pages#home'
  get '/home',       to: 'static_pages#home'
  get '/about',      to: 'static_pages#about'
  get '/resume',     to: 'static_pages#resume'
  get '/services',   to: 'static_pages#services'
  get '/contact',    to: 'static_pages#contact'
  resources :messages
  resources :documents
  resources :clients
  resources :bills
  resources :users do
    member do
      get :messages
      get :clients
      get :bills
      get :documents
    end
    resources :messages 
    resources :clients
    resources :bills
    resources :documents
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/_footer.html.erb
<footer class="footer container col-md-12 col-sm-12 col-xs-12">
  <small>
    <div class='foot-text foot col-md-4 col-sm-6 col-xs-6'>
      Discover Family History | Gail Shaffer Blankenau
    </div>
    <nav class='foot-nav col-md-8 col-sm-6 col-xs-6'>
      <ul class='col-md-8 col-sm-12 col-xs-12 pull-right'>
        <li class='pull-right social_img col-md-4 col-sm-6 col-xs-12'>
              <%= link_to 'https://www.facebook.com/discoveringfamilyhistory/', title: 'Discover Family History on Facebook' do %>
                <%= image_tag('book.jpg') =%>
              <% end %>
        </li>
        <li class='pull-right social_img col-md-4 col-sm-6 col-xs-12'>
              <%= link_to 'https://twitter.com/GailBlankenau', title: 'Discover Family History on Twitter' do %>
                <%= image_tag('bird.jpg') =%>
              <% end %>
        </li>
        <li class='foot-text pull-right'><%= link_to "Contact", contact_path, title: 'Send A Message' %></li>
        <li class='foot-text pull-right'><%= link_to "About",   about_path, title: 'About' %></li>
      </ul>
    </nav>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse col-md-12 col-sm-12 col-xs-12'>
  <div class='container'>
    <div class='col-md-8 col-sm-8 col-xs-7'>
      <%= image_tag('logo.png', :class => 'col-md-1 col-sm-2 col-xs-3 logo-img') =%>
      <div class='col-md-9 col-sm-7 col-xs-12'>
        <%= link_to 'Discover Family History', home_path, id: 'logo' %>
      </div>
    </div>
    <nav class='col-md-4 col-sm-4 col-xs-5 pull-right'>
      <ul class='nav navbar-nav navbar-right'>
       <li class="dropdown menu">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Menu
        <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Home', home_path %></li>
                <li><%= link_to 'About', about_path %></li>
                <li><%= link_to 'Resume', resume_path %></li>
                <li><%= link_to 'Services', services_path %></li>
                <li><%= link_to 'Contact Me', contact_path %></li>
            </ul>
      </li>
    </ul>
    </nav>
  </div>
  <a class='header-link center col-md-12 col-sm-12 col-xs-12' href='https://familytreewebinars.com/gailblankenau'>Click here to subsrcibe to Legacy Family Tree and see webinars featuring Gail!</a>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= full_title(yield(:title)) %>
  </title>
  <%= favicon_link_tag 'logo.png' %>
  <%= stylesheet_link_tag 'home' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class='container'>
    <div class='info message'>
      <% flash.each do |message_type, message| %>
    </div>
      <%= content_tag(:div, message, class: "alet alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>